---
title: "check for input table to Mosaic plot"
author: "kazuo.fujimoto2007@gmail.com"
date: "2025-05-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
load(file = "cyder2024a_all.df.rda")
```


```{r}
data_for_plot <- cyder2024a.all.df
data_for_plot %>% names


select_input_data_for_cross <- "年齢" 
variables <- "性別" 

input <- data_for_plot

input$select_input_data_for_cross
input$variables[1]

    output$crosschart <- renderPlot({
      .tbl <- table(data_for_plot()[,input$select_input_data_for_cross],
                    data_for_plot()[,input$variables[1]])  #select_input_data_for_hist
      .tbl.p <- round(100 * prop.table(.tbl ,margin = 1),1)
      tab <- ifelse(.tbl.p < 1, NA, .tbl.p)

      data_for_plot()[,c(input$variables[1],     #select_input_data_for_hist,
                         input$select_input_data_for_cross)] %>%
        structable() %>%
        mosaic(shade=TRUE,las=2,
               labeling=labeling_values
        )
    })
```

```{r}
df <- cyder2024a.all.df
vari1 <- "年齢" 
vari2 <- "性別"

.tbl <- table(df[,vari1],
              df[,vari2])


.tbl <- table(df[[vari1]],
              df[[vari2]])

.tbl <- with(df, table(vari1,vari2))
.tbl
```

